[package]
name = "secret-toolkit"
version = "0.1.0"
edition = "2018"

[dependencies]
secret-toolkit-crypto = { path = "../crypto" }
secret-toolkit-serialization = { path = "../serialization" }
secret-toolkit-storage = { path = "../storage" }
secret-toolkit-utils = { path = "../utils" }
secret-toolkit-snip20 = { path = "../snip20" }
